language: elixir
services:
  - postgresql
cache:
  directories:
    - $HOME/.mix
elixir:
  - 1.8.1
  - 1.9.1
otp_release:
  - 20.3
  - 21.3
  - 22.0
script:
  - bin/setup
before_script:
  - psql -c 'create database example_test;' -U postgres
env:
  - MIX_ENV=test DATABASE_POSTGRESQL_USERNAME=postgres
