language: elixir
services:
  - postgresql
cache:
  directories:
    - $HOME/.mix
elixir:
  - 1.8.0
otp_release:
  - 20.1
script:
  - bin/setup
before_script:
  - psql -c 'create database example_test;' -U postgres
env:
  - DATABASE_POSTGRESQL_USERNAME=postgres
